# frozen_string_literal: true

# This file is auto-generated from the Discourse database schema. To make changes, update
# the "config/intermediate_db.yml" configuration file and then run `cli schema generate` to
# regenerate this file.

module Migrations::Database::IntermediateDB
  module Post
    SQL = <<~SQL
      INSERT INTO posts (
        id,
        action_code,
        baked_at,
        baked_version,
        bookmark_count,
        cook_method,
        cooked,
        created_at,
        deleted_at,
        deleted_by_id,
        edit_reason,
        hidden,
        hidden_at,
        hidden_reason_id,
        illegal_count,
        image_upload_id,
        inappropriate_count,
        incoming_link_count,
        last_editor_id,
        last_version_at,
        like_count,
        like_score,
        locked_by_id,
        notify_moderators_count,
        notify_user_count,
        off_topic_count,
        outbound_message_id,
        percent_rank,
        post_number,
        post_type,
        public_version,
        quote_count,
        raw,
        raw_email,
        reads,
        reply_count,
        reply_quoted,
        reply_to_post_number,
        reply_to_user_id,
        score,
        self_edits,
        sort_order,
        spam_count,
        topic_id,
        user_deleted,
        user_id,
        version,
        via_email,
        wiki,
        word_count
      )
      VALUES (
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
      )
    SQL
  end

  def self.create!(
    id:,
    action_code: nil,
    baked_at: nil,
    baked_version: nil,
    bookmark_count: nil,
    cook_method: nil,
    cooked:,
    created_at:,
    deleted_at: nil,
    deleted_by_id: nil,
    edit_reason: nil,
    hidden: nil,
    hidden_at: nil,
    hidden_reason_id: nil,
    illegal_count: nil,
    image_upload_id: nil,
    inappropriate_count: nil,
    incoming_link_count: nil,
    last_editor_id: nil,
    last_version_at:,
    like_count: nil,
    like_score: nil,
    locked_by_id: nil,
    notify_moderators_count: nil,
    notify_user_count: nil,
    off_topic_count: nil,
    outbound_message_id: nil,
    percent_rank: nil,
    post_number:,
    post_type: nil,
    public_version: nil,
    quote_count: nil,
    raw:,
    raw_email: nil,
    reads: nil,
    reply_count: nil,
    reply_quoted: nil,
    reply_to_post_number: nil,
    reply_to_user_id: nil,
    score: nil,
    self_edits: nil,
    sort_order: nil,
    spam_count: nil,
    topic_id:,
    user_deleted: nil,
    user_id: nil,
    version: nil,
    via_email: nil,
    wiki: nil,
    word_count: nil
  )
    ::Migrations::Database::IntermediateDB.insert(
      id:,
      action_code:,
      baked_at:,
      baked_version:,
      bookmark_count:,
      cook_method:,
      cooked:,
      created_at:,
      deleted_at:,
      deleted_by_id:,
      edit_reason:,
      hidden:,
      hidden_at:,
      hidden_reason_id:,
      illegal_count:,
      image_upload_id:,
      inappropriate_count:,
      incoming_link_count:,
      last_editor_id:,
      last_version_at:,
      like_count:,
      like_score:,
      locked_by_id:,
      notify_moderators_count:,
      notify_user_count:,
      off_topic_count:,
      outbound_message_id:,
      percent_rank:,
      post_number:,
      post_type:,
      public_version:,
      quote_count:,
      raw:,
      raw_email:,
      reads:,
      reply_count:,
      reply_quoted:,
      reply_to_post_number:,
      reply_to_user_id:,
      score:,
      self_edits:,
      sort_order:,
      spam_count:,
      topic_id:,
      user_deleted:,
      user_id:,
      version:,
      via_email:,
      wiki:,
      word_count:,
    )
  end
end
