-- This file is auto-generated from the Discourse database schema. To make changes, update
-- the "config/intermediate_db.yml" configuration file and then run `cli schema generate` to
-- regenerate this file.

CREATE TABLE posts
(
    id                      NUMERIC  NOT NULL PRIMARY KEY,
    action_code             TEXT,
    baked_at                DATETIME,
    baked_version           INTEGER,
    bookmark_count          INTEGER,
    cook_method             INTEGER,
    cooked                  TEXT     NOT NULL,
    created_at              DATETIME NOT NULL,
    deleted_at              DATETIME,
    deleted_by_id           NUMERIC,
    edit_reason             TEXT,
    hidden                  BOOLEAN,
    hidden_at               DATETIME,
    hidden_reason_id        NUMERIC,
    illegal_count           INTEGER,
    image_upload_id         NUMERIC,
    inappropriate_count     INTEGER,
    incoming_link_count     INTEGER,
    last_editor_id          NUMERIC,
    last_version_at         DATETIME NOT NULL,
    like_count              INTEGER,
    like_score              INTEGER,
    locked_by_id            NUMERIC,
    notify_moderators_count INTEGER,
    notify_user_count       INTEGER,
    off_topic_count         INTEGER,
    outbound_message_id     NUMERIC,
    percent_rank            FLOAT,
    post_number             INTEGER  NOT NULL,
    post_type               INTEGER,
    public_version          INTEGER,
    quote_count             INTEGER,
    raw                     TEXT     NOT NULL,
    raw_email               TEXT,
    reads                   INTEGER,
    reply_count             INTEGER,
    reply_quoted            BOOLEAN,
    reply_to_post_number    INTEGER,
    reply_to_user_id        NUMERIC,
    score                   FLOAT,
    self_edits              INTEGER,
    sort_order              INTEGER,
    spam_count              INTEGER,
    topic_id                NUMERIC  NOT NULL,
    user_deleted            BOOLEAN,
    user_id                 NUMERIC,
    version                 INTEGER,
    via_email               BOOLEAN,
    wiki                    BOOLEAN,
    word_count              INTEGER
);

CREATE TABLE users
(
    id                        NUMERIC  NOT NULL PRIMARY KEY,
    active                    BOOLEAN,
    admin                     BOOLEAN,
    approved                  BOOLEAN,
    approved_at               DATETIME,
    approved_by_id            NUMERIC,
    created_at                DATETIME NOT NULL,
    date_of_birth             DATE,
    first_seen_at             DATETIME,
    flair_group_id            NUMERIC,
    group_locked_trust_level  INTEGER,
    ip_address                INET_TEXT,
    last_seen_at              DATETIME,
    locale                    TEXT,
    manual_locked_trust_level INTEGER,
    moderator                 BOOLEAN,
    name                      TEXT,
    previous_visit_at         DATETIME,
    primary_group_id          NUMERIC,
    registration_ip_address   INET_TEXT,
    required_fields_version   INTEGER,
    silenced_till             DATETIME,
    staged                    BOOLEAN,
    suspended_at              DATETIME,
    suspended_till            DATETIME,
    title                     TEXT,
    trust_level               INTEGER  NOT NULL,
    uploaded_avatar_id        NUMERIC,
    username                  TEXT     NOT NULL,
    views                     INTEGER
);

